demo-project:
  display-name: demo-project-local

mpseguranca:
  seguranca:
    excecoes-actuator: info,health,env
    excecoes: /swagger-*,/v2/api-docs,/swagger-*/**,/webjars/**,/error,/mp-dialga/seguranca/lojista,/mp-compras/**,/mp-pas/**
    autoridades: ADMIN,READ,WRITE

spring:
  banner:
    location: classpath:banner.txt

logging:
  file: logs/${demo-project.display-name}.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    root: INFO
    org:
      springframework: INFO
    br.com.demo.demo-project.core.adminAuthenticationServicesWeb.feign.ApiAdminAuthenticationServicesWeb: TRACE

feign:
  configuration:
    connectTimeoutMilis: 30000
    readTimeoutMilis: 60000

messages:
  basename: messages
  defaultCountry: BR
  defaultLanguage: PT
  defaultEncoding: UTF-8
  default:
    country: BR
    language: PT
    encoding: UTF-8